### ISSUE TITLE
Fail a CI build if projects not alphabetical

### ISSUE THREAD

**Issue by jchannon** [mysticmind/dotnet-sort-refs#3]
I was wondering if the tool could offer an option to exit with an error code if projects are not alphabetical.

My thoughts being if someone on my team change a csproj and its not alphabetical the CI server can fail the build

**Comment by mysticmind** [comment]
Sure, will look at adding it.

**Comment by mysticmind** [comment]
Feature added and will be available in v0.2.0

**Comment by mysticmind** [comment]
Apart from returning a non-zero return code if one or more projects have non-sorted package references, a nice inspection report is printed to console as below:
![image](https://user-images.githubusercontent.com/2864208/72265625-d0f9e180-3642-11ea-9aa9-628788de6d49.png)

**Comment by jchannon** [comment]
Ha! This is brilliant.

Thanks so much!
